from django.urls import include, path
from .views import AircraftList, AircraftSearch, AircraftById, AircraftByName, AccidentsList, upload_csv, upload_accidents, process_webhook, update_limitation
from .mongo_utils import LiveFlights, FlightsByPeriod, FlightsByContinent, FlightsByMake, DomesticVsInternationalFlights, FlightsByCategory, FlightsByCountry, FlightsByCity, StockPrices, FlightsByMonthForYear, FlightHoursHistory, FlightDistanceHistory, FlightHistory, LatestNews, FlightsByAirport, Registrations, Accidents, TopRoutes, AircraftLookup, GetAircraftData, RegNumbersForAircraft, GetAvgAnnualHoursAndDistance, GetLast12MonthsFlights, GetLast60DaysFlights, GetFleetActivity, GetFleetData, GetFlightsForPreviousYears, GetAIIndustryOverview, GetAIAircraftOverview, GetIndustryHealth, GetAircraftHealth, GetAIAircraftLookup

urlpatterns = [
    path("search/", AircraftSearch.as_view()),
    path("new-search/", AircraftSearch.as_view()),
    path('aircrafts/<int:id>/', AircraftById.as_view()),
    path('aircraft-by-name/<str:name>/', AircraftByName.as_view()),
    path("aircraft-items/", GetAircraftData.as_view()),
    path("accident-items/", AccidentsList.as_view()),
    path('live-flights/', LiveFlights.as_view()),
    path('flights-by-period/', FlightsByPeriod.as_view()),
    path('flights-by-continent/<int:days>/', FlightsByContinent.as_view()),
    path('flights-by-category/<int:days>/', FlightsByCategory.as_view()),
    path('flights-by-make/<int:days>/', FlightsByMake.as_view()),
    path('domestic-vs-int/<int:days>/', DomesticVsInternationalFlights.as_view()),
    path('flights-by-airport/<int:days>/', FlightsByAirport.as_view()),
    path('flights-by-city/<int:days>/', FlightsByCity.as_view()),
    path('flights-by-country/<int:days>/', FlightsByCountry.as_view()),
    path('flight-history/', FlightHistory.as_view()),
    path('flight-hours-history/', FlightHoursHistory.as_view()),
    path('flight-distance-history/', FlightDistanceHistory.as_view()),
    path('flights-by-month-for-year/<int:year>/', FlightsByMonthForYear.as_view()),
    path('top-routes/<int:days>/', TopRoutes.as_view()),
    path('stock-prices/', StockPrices.as_view()),
    path('latest-news/', LatestNews.as_view()),
    path('registrations/', Registrations.as_view()),
    path('accidents/', Accidents.as_view()),
    path('reg-numbers-for-aircraft/', RegNumbersForAircraft.as_view()),
    path('avg-annual-hours-and-distance/', GetAvgAnnualHoursAndDistance.as_view()),
    path('sixty-day-flight-history/', GetLast60DaysFlights.as_view()),
    path('flights-for-previous-years/', GetFlightsForPreviousYears.as_view()),
    path('last-12-months-flights/', GetLast12MonthsFlights.as_view()),
    path('aircraft-lookup/<str:reg>/', AircraftLookup.as_view()),
    path('fleet-activity/', GetFleetActivity.as_view()),
    path('fleet-data/', GetFleetData.as_view()),
    path("add-user/", process_webhook, name="add-user"),
    path('upload-csv/', upload_csv, name="upload-csv"),
    path('upload-accidents/', upload_accidents, name="upload-accidents"),
    path('ai-industry-overview/<str:question>', GetAIIndustryOverview.as_view()),
    path('ai-aircraft-lookup/<str:reg>/<str:question>', GetAIAircraftLookup.as_view()),
    path('ai-aircraft-overview/<str:aircraft>/<str:question>', GetAIAircraftOverview.as_view()),
    path('ai-health-industry/', GetIndustryHealth.as_view()),
    path('ai-health-aircraft/', GetAircraftHealth.as_view()),
    path('update-limitation/', update_limitation)
]
